# Generated by Django 4.1.7 on 2023-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_link_course_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
